/*
 * This file is generated by jOOQ.
 */
package persistence.db.tables.records;


import java.math.BigDecimal;
import java.util.UUID;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;

import persistence.db.tables.PurchaseHistory;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PurchaseHistoryRecord extends TableRecordImpl<PurchaseHistoryRecord> implements Record4<UUID, UUID, UUID, BigDecimal> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.purchase_history.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.purchase_history.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.purchase_history.customers_id</code>.
     */
    public void setCustomersId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.purchase_history.customers_id</code>.
     */
    public UUID getCustomersId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.purchase_history.card_id</code>.
     */
    public void setCardId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.purchase_history.card_id</code>.
     */
    public UUID getCardId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.purchase_history.total_value</code>.
     */
    public void setTotalValue(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.purchase_history.total_value</code>.
     */
    public BigDecimal getTotalValue() {
        return (BigDecimal) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row4<UUID, UUID, UUID, BigDecimal> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    @Override
    public Row4<UUID, UUID, UUID, BigDecimal> valuesRow() {
        return (Row4) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return PurchaseHistory.PURCHASE_HISTORY.ID;
    }

    @Override
    public Field<UUID> field2() {
        return PurchaseHistory.PURCHASE_HISTORY.CUSTOMERS_ID;
    }

    @Override
    public Field<UUID> field3() {
        return PurchaseHistory.PURCHASE_HISTORY.CARD_ID;
    }

    @Override
    public Field<BigDecimal> field4() {
        return PurchaseHistory.PURCHASE_HISTORY.TOTAL_VALUE;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public UUID component2() {
        return getCustomersId();
    }

    @Override
    public UUID component3() {
        return getCardId();
    }

    @Override
    public BigDecimal component4() {
        return getTotalValue();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public UUID value2() {
        return getCustomersId();
    }

    @Override
    public UUID value3() {
        return getCardId();
    }

    @Override
    public BigDecimal value4() {
        return getTotalValue();
    }

    @Override
    public PurchaseHistoryRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public PurchaseHistoryRecord value2(UUID value) {
        setCustomersId(value);
        return this;
    }

    @Override
    public PurchaseHistoryRecord value3(UUID value) {
        setCardId(value);
        return this;
    }

    @Override
    public PurchaseHistoryRecord value4(BigDecimal value) {
        setTotalValue(value);
        return this;
    }

    @Override
    public PurchaseHistoryRecord values(UUID value1, UUID value2, UUID value3, BigDecimal value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PurchaseHistoryRecord
     */
    public PurchaseHistoryRecord() {
        super(PurchaseHistory.PURCHASE_HISTORY);
    }

    /**
     * Create a detached, initialised PurchaseHistoryRecord
     */
    public PurchaseHistoryRecord(UUID id, UUID customersId, UUID cardId, BigDecimal totalValue) {
        super(PurchaseHistory.PURCHASE_HISTORY);

        setId(id);
        setCustomersId(customersId);
        setCardId(cardId);
        setTotalValue(totalValue);
    }
}
