/*
 * This file is generated by jOOQ.
 */
package persistence.db;


import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;

import persistence.db.routines.Armor1;
import persistence.db.routines.Armor2;
import persistence.db.routines.Crypt;
import persistence.db.routines.Dearmor;
import persistence.db.routines.Decrypt;
import persistence.db.routines.DecryptIv;
import persistence.db.routines.Digest1;
import persistence.db.routines.Digest2;
import persistence.db.routines.Encrypt;
import persistence.db.routines.EncryptIv;
import persistence.db.routines.GenRandomBytes;
import persistence.db.routines.GenRandomUuid;
import persistence.db.routines.GenSalt1;
import persistence.db.routines.GenSalt2;
import persistence.db.routines.Hmac1;
import persistence.db.routines.Hmac2;
import persistence.db.routines.PgpKeyId;
import persistence.db.routines.PgpPubDecrypt1;
import persistence.db.routines.PgpPubDecrypt2;
import persistence.db.routines.PgpPubDecrypt3;
import persistence.db.routines.PgpPubDecryptBytea1;
import persistence.db.routines.PgpPubDecryptBytea2;
import persistence.db.routines.PgpPubDecryptBytea3;
import persistence.db.routines.PgpPubEncrypt1;
import persistence.db.routines.PgpPubEncrypt2;
import persistence.db.routines.PgpPubEncryptBytea1;
import persistence.db.routines.PgpPubEncryptBytea2;
import persistence.db.routines.PgpSymDecrypt1;
import persistence.db.routines.PgpSymDecrypt2;
import persistence.db.routines.PgpSymDecryptBytea1;
import persistence.db.routines.PgpSymDecryptBytea2;
import persistence.db.routines.PgpSymEncrypt1;
import persistence.db.routines.PgpSymEncrypt2;
import persistence.db.routines.PgpSymEncryptBytea1;
import persistence.db.routines.PgpSymEncryptBytea2;
import persistence.db.routines.UuidGenerateV1;
import persistence.db.routines.UuidGenerateV1mc;
import persistence.db.routines.UuidGenerateV3;
import persistence.db.routines.UuidGenerateV4;
import persistence.db.routines.UuidGenerateV5;
import persistence.db.routines.UuidNil;
import persistence.db.routines.UuidNsDns;
import persistence.db.routines.UuidNsOid;
import persistence.db.routines.UuidNsUrl;
import persistence.db.routines.UuidNsX500;
import persistence.db.tables.PgpArmorHeaders;
import persistence.db.tables.records.PgpArmorHeadersRecord;


/**
 * Convenience access to all stored procedures and functions in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.armor</code>
     */
    public static String armor1(
          Configuration configuration
        , byte[] __1
    ) {
        Armor1 f = new Armor1();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.armor</code> as a field.
     */
    public static Field<String> armor1(
          byte[] __1
    ) {
        Armor1 f = new Armor1();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.armor</code> as a field.
     */
    public static Field<String> armor1(
          Field<byte[]> __1
    ) {
        Armor1 f = new Armor1();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>public.armor</code>
     */
    public static String armor2(
          Configuration configuration
        , byte[] __1
        , String[] __2
        , String[] __3
    ) {
        Armor2 f = new Armor2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.armor</code> as a field.
     */
    public static Field<String> armor2(
          byte[] __1
        , String[] __2
        , String[] __3
    ) {
        Armor2 f = new Armor2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.armor</code> as a field.
     */
    public static Field<String> armor2(
          Field<byte[]> __1
        , Field<String[]> __2
        , Field<String[]> __3
    ) {
        Armor2 f = new Armor2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.crypt</code>
     */
    public static String crypt(
          Configuration configuration
        , String __1
        , String __2
    ) {
        Crypt f = new Crypt();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.crypt</code> as a field.
     */
    public static Field<String> crypt(
          String __1
        , String __2
    ) {
        Crypt f = new Crypt();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.crypt</code> as a field.
     */
    public static Field<String> crypt(
          Field<String> __1
        , Field<String> __2
    ) {
        Crypt f = new Crypt();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.dearmor</code>
     */
    public static byte[] dearmor(
          Configuration configuration
        , String __1
    ) {
        Dearmor f = new Dearmor();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.dearmor</code> as a field.
     */
    public static Field<byte[]> dearmor(
          String __1
    ) {
        Dearmor f = new Dearmor();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.dearmor</code> as a field.
     */
    public static Field<byte[]> dearmor(
          Field<String> __1
    ) {
        Dearmor f = new Dearmor();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>public.decrypt</code>
     */
    public static byte[] decrypt(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        Decrypt f = new Decrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.decrypt</code> as a field.
     */
    public static Field<byte[]> decrypt(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        Decrypt f = new Decrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.decrypt</code> as a field.
     */
    public static Field<byte[]> decrypt(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        Decrypt f = new Decrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.decrypt_iv</code>
     */
    public static byte[] decryptIv(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , byte[] __3
        , String __4
    ) {
        DecryptIv f = new DecryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.decrypt_iv</code> as a field.
     */
    public static Field<byte[]> decryptIv(
          byte[] __1
        , byte[] __2
        , byte[] __3
        , String __4
    ) {
        DecryptIv f = new DecryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Get <code>public.decrypt_iv</code> as a field.
     */
    public static Field<byte[]> decryptIv(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<byte[]> __3
        , Field<String> __4
    ) {
        DecryptIv f = new DecryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Call <code>public.digest</code>
     */
    public static byte[] digest1(
          Configuration configuration
        , String __1
        , String __2
    ) {
        Digest1 f = new Digest1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.digest</code> as a field.
     */
    public static Field<byte[]> digest1(
          String __1
        , String __2
    ) {
        Digest1 f = new Digest1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.digest</code> as a field.
     */
    public static Field<byte[]> digest1(
          Field<String> __1
        , Field<String> __2
    ) {
        Digest1 f = new Digest1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.digest</code>
     */
    public static byte[] digest2(
          Configuration configuration
        , byte[] __1
        , String __2
    ) {
        Digest2 f = new Digest2();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.digest</code> as a field.
     */
    public static Field<byte[]> digest2(
          byte[] __1
        , String __2
    ) {
        Digest2 f = new Digest2();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.digest</code> as a field.
     */
    public static Field<byte[]> digest2(
          Field<byte[]> __1
        , Field<String> __2
    ) {
        Digest2 f = new Digest2();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.encrypt</code>
     */
    public static byte[] encrypt(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        Encrypt f = new Encrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.encrypt</code> as a field.
     */
    public static Field<byte[]> encrypt(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        Encrypt f = new Encrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.encrypt</code> as a field.
     */
    public static Field<byte[]> encrypt(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        Encrypt f = new Encrypt();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.encrypt_iv</code>
     */
    public static byte[] encryptIv(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , byte[] __3
        , String __4
    ) {
        EncryptIv f = new EncryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.encrypt_iv</code> as a field.
     */
    public static Field<byte[]> encryptIv(
          byte[] __1
        , byte[] __2
        , byte[] __3
        , String __4
    ) {
        EncryptIv f = new EncryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Get <code>public.encrypt_iv</code> as a field.
     */
    public static Field<byte[]> encryptIv(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<byte[]> __3
        , Field<String> __4
    ) {
        EncryptIv f = new EncryptIv();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Call <code>public.gen_random_bytes</code>
     */
    public static byte[] genRandomBytes(
          Configuration configuration
        , Integer __1
    ) {
        GenRandomBytes f = new GenRandomBytes();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.gen_random_bytes</code> as a field.
     */
    public static Field<byte[]> genRandomBytes(
          Integer __1
    ) {
        GenRandomBytes f = new GenRandomBytes();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.gen_random_bytes</code> as a field.
     */
    public static Field<byte[]> genRandomBytes(
          Field<Integer> __1
    ) {
        GenRandomBytes f = new GenRandomBytes();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>public.gen_random_uuid</code>
     */
    public static UUID genRandomUuid(
          Configuration configuration
    ) {
        GenRandomUuid f = new GenRandomUuid();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.gen_random_uuid</code> as a field.
     */
    public static Field<UUID> genRandomUuid() {
        GenRandomUuid f = new GenRandomUuid();

        return f.asField();
    }

    /**
     * Call <code>public.gen_salt</code>
     */
    public static String genSalt1(
          Configuration configuration
        , String __1
    ) {
        GenSalt1 f = new GenSalt1();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.gen_salt</code> as a field.
     */
    public static Field<String> genSalt1(
          String __1
    ) {
        GenSalt1 f = new GenSalt1();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.gen_salt</code> as a field.
     */
    public static Field<String> genSalt1(
          Field<String> __1
    ) {
        GenSalt1 f = new GenSalt1();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>public.gen_salt</code>
     */
    public static String genSalt2(
          Configuration configuration
        , String __1
        , Integer __2
    ) {
        GenSalt2 f = new GenSalt2();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.gen_salt</code> as a field.
     */
    public static Field<String> genSalt2(
          String __1
        , Integer __2
    ) {
        GenSalt2 f = new GenSalt2();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.gen_salt</code> as a field.
     */
    public static Field<String> genSalt2(
          Field<String> __1
        , Field<Integer> __2
    ) {
        GenSalt2 f = new GenSalt2();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.hmac</code>
     */
    public static byte[] hmac1(
          Configuration configuration
        , String __1
        , String __2
        , String __3
    ) {
        Hmac1 f = new Hmac1();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.hmac</code> as a field.
     */
    public static Field<byte[]> hmac1(
          String __1
        , String __2
        , String __3
    ) {
        Hmac1 f = new Hmac1();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.hmac</code> as a field.
     */
    public static Field<byte[]> hmac1(
          Field<String> __1
        , Field<String> __2
        , Field<String> __3
    ) {
        Hmac1 f = new Hmac1();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.hmac</code>
     */
    public static byte[] hmac2(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        Hmac2 f = new Hmac2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.hmac</code> as a field.
     */
    public static Field<byte[]> hmac2(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        Hmac2 f = new Hmac2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.hmac</code> as a field.
     */
    public static Field<byte[]> hmac2(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        Hmac2 f = new Hmac2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_key_id</code>
     */
    public static String pgpKeyId(
          Configuration configuration
        , byte[] __1
    ) {
        PgpKeyId f = new PgpKeyId();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_key_id</code> as a field.
     */
    public static Field<String> pgpKeyId(
          byte[] __1
    ) {
        PgpKeyId f = new PgpKeyId();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_key_id</code> as a field.
     */
    public static Field<String> pgpKeyId(
          Field<byte[]> __1
    ) {
        PgpKeyId f = new PgpKeyId();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt</code>
     */
    public static String pgpPubDecrypt1(
          Configuration configuration
        , byte[] __1
        , byte[] __2
    ) {
        PgpPubDecrypt1 f = new PgpPubDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt1(
          byte[] __1
        , byte[] __2
    ) {
        PgpPubDecrypt1 f = new PgpPubDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt1(
          Field<byte[]> __1
        , Field<byte[]> __2
    ) {
        PgpPubDecrypt1 f = new PgpPubDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt</code>
     */
    public static String pgpPubDecrypt2(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubDecrypt2 f = new PgpPubDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt2(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubDecrypt2 f = new PgpPubDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt2(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        PgpPubDecrypt2 f = new PgpPubDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt</code>
     */
    public static String pgpPubDecrypt3(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
        , String __4
    ) {
        PgpPubDecrypt3 f = new PgpPubDecrypt3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt3(
          byte[] __1
        , byte[] __2
        , String __3
        , String __4
    ) {
        PgpPubDecrypt3 f = new PgpPubDecrypt3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt</code> as a field.
     */
    public static Field<String> pgpPubDecrypt3(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
        , Field<String> __4
    ) {
        PgpPubDecrypt3 f = new PgpPubDecrypt3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt_bytea</code>
     */
    public static byte[] pgpPubDecryptBytea1(
          Configuration configuration
        , byte[] __1
        , byte[] __2
    ) {
        PgpPubDecryptBytea1 f = new PgpPubDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea1(
          byte[] __1
        , byte[] __2
    ) {
        PgpPubDecryptBytea1 f = new PgpPubDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea1(
          Field<byte[]> __1
        , Field<byte[]> __2
    ) {
        PgpPubDecryptBytea1 f = new PgpPubDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt_bytea</code>
     */
    public static byte[] pgpPubDecryptBytea2(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubDecryptBytea2 f = new PgpPubDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea2(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubDecryptBytea2 f = new PgpPubDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea2(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        PgpPubDecryptBytea2 f = new PgpPubDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_decrypt_bytea</code>
     */
    public static byte[] pgpPubDecryptBytea3(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
        , String __4
    ) {
        PgpPubDecryptBytea3 f = new PgpPubDecryptBytea3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea3(
          byte[] __1
        , byte[] __2
        , String __3
        , String __4
    ) {
        PgpPubDecryptBytea3 f = new PgpPubDecryptBytea3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubDecryptBytea3(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
        , Field<String> __4
    ) {
        PgpPubDecryptBytea3 f = new PgpPubDecryptBytea3();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);
        f.set__4(__4);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_encrypt</code>
     */
    public static byte[] pgpPubEncrypt1(
          Configuration configuration
        , String __1
        , byte[] __2
    ) {
        PgpPubEncrypt1 f = new PgpPubEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpPubEncrypt1(
          String __1
        , byte[] __2
    ) {
        PgpPubEncrypt1 f = new PgpPubEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpPubEncrypt1(
          Field<String> __1
        , Field<byte[]> __2
    ) {
        PgpPubEncrypt1 f = new PgpPubEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_encrypt</code>
     */
    public static byte[] pgpPubEncrypt2(
          Configuration configuration
        , String __1
        , byte[] __2
        , String __3
    ) {
        PgpPubEncrypt2 f = new PgpPubEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpPubEncrypt2(
          String __1
        , byte[] __2
        , String __3
    ) {
        PgpPubEncrypt2 f = new PgpPubEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpPubEncrypt2(
          Field<String> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        PgpPubEncrypt2 f = new PgpPubEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_encrypt_bytea</code>
     */
    public static byte[] pgpPubEncryptBytea1(
          Configuration configuration
        , byte[] __1
        , byte[] __2
    ) {
        PgpPubEncryptBytea1 f = new PgpPubEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubEncryptBytea1(
          byte[] __1
        , byte[] __2
    ) {
        PgpPubEncryptBytea1 f = new PgpPubEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubEncryptBytea1(
          Field<byte[]> __1
        , Field<byte[]> __2
    ) {
        PgpPubEncryptBytea1 f = new PgpPubEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_pub_encrypt_bytea</code>
     */
    public static byte[] pgpPubEncryptBytea2(
          Configuration configuration
        , byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubEncryptBytea2 f = new PgpPubEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_pub_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubEncryptBytea2(
          byte[] __1
        , byte[] __2
        , String __3
    ) {
        PgpPubEncryptBytea2 f = new PgpPubEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_pub_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpPubEncryptBytea2(
          Field<byte[]> __1
        , Field<byte[]> __2
        , Field<String> __3
    ) {
        PgpPubEncryptBytea2 f = new PgpPubEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_decrypt</code>
     */
    public static String pgpSymDecrypt1(
          Configuration configuration
        , byte[] __1
        , String __2
    ) {
        PgpSymDecrypt1 f = new PgpSymDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_decrypt</code> as a field.
     */
    public static Field<String> pgpSymDecrypt1(
          byte[] __1
        , String __2
    ) {
        PgpSymDecrypt1 f = new PgpSymDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_decrypt</code> as a field.
     */
    public static Field<String> pgpSymDecrypt1(
          Field<byte[]> __1
        , Field<String> __2
    ) {
        PgpSymDecrypt1 f = new PgpSymDecrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_decrypt</code>
     */
    public static String pgpSymDecrypt2(
          Configuration configuration
        , byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymDecrypt2 f = new PgpSymDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_decrypt</code> as a field.
     */
    public static Field<String> pgpSymDecrypt2(
          byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymDecrypt2 f = new PgpSymDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_decrypt</code> as a field.
     */
    public static Field<String> pgpSymDecrypt2(
          Field<byte[]> __1
        , Field<String> __2
        , Field<String> __3
    ) {
        PgpSymDecrypt2 f = new PgpSymDecrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_decrypt_bytea</code>
     */
    public static byte[] pgpSymDecryptBytea1(
          Configuration configuration
        , byte[] __1
        , String __2
    ) {
        PgpSymDecryptBytea1 f = new PgpSymDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymDecryptBytea1(
          byte[] __1
        , String __2
    ) {
        PgpSymDecryptBytea1 f = new PgpSymDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymDecryptBytea1(
          Field<byte[]> __1
        , Field<String> __2
    ) {
        PgpSymDecryptBytea1 f = new PgpSymDecryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_decrypt_bytea</code>
     */
    public static byte[] pgpSymDecryptBytea2(
          Configuration configuration
        , byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymDecryptBytea2 f = new PgpSymDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymDecryptBytea2(
          byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymDecryptBytea2 f = new PgpSymDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_decrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymDecryptBytea2(
          Field<byte[]> __1
        , Field<String> __2
        , Field<String> __3
    ) {
        PgpSymDecryptBytea2 f = new PgpSymDecryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_encrypt</code>
     */
    public static byte[] pgpSymEncrypt1(
          Configuration configuration
        , String __1
        , String __2
    ) {
        PgpSymEncrypt1 f = new PgpSymEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpSymEncrypt1(
          String __1
        , String __2
    ) {
        PgpSymEncrypt1 f = new PgpSymEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpSymEncrypt1(
          Field<String> __1
        , Field<String> __2
    ) {
        PgpSymEncrypt1 f = new PgpSymEncrypt1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_encrypt</code>
     */
    public static byte[] pgpSymEncrypt2(
          Configuration configuration
        , String __1
        , String __2
        , String __3
    ) {
        PgpSymEncrypt2 f = new PgpSymEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpSymEncrypt2(
          String __1
        , String __2
        , String __3
    ) {
        PgpSymEncrypt2 f = new PgpSymEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_encrypt</code> as a field.
     */
    public static Field<byte[]> pgpSymEncrypt2(
          Field<String> __1
        , Field<String> __2
        , Field<String> __3
    ) {
        PgpSymEncrypt2 f = new PgpSymEncrypt2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_encrypt_bytea</code>
     */
    public static byte[] pgpSymEncryptBytea1(
          Configuration configuration
        , byte[] __1
        , String __2
    ) {
        PgpSymEncryptBytea1 f = new PgpSymEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymEncryptBytea1(
          byte[] __1
        , String __2
    ) {
        PgpSymEncryptBytea1 f = new PgpSymEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymEncryptBytea1(
          Field<byte[]> __1
        , Field<String> __2
    ) {
        PgpSymEncryptBytea1 f = new PgpSymEncryptBytea1();
        f.set__1(__1);
        f.set__2(__2);

        return f.asField();
    }

    /**
     * Call <code>public.pgp_sym_encrypt_bytea</code>
     */
    public static byte[] pgpSymEncryptBytea2(
          Configuration configuration
        , byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymEncryptBytea2 f = new PgpSymEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.pgp_sym_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymEncryptBytea2(
          byte[] __1
        , String __2
        , String __3
    ) {
        PgpSymEncryptBytea2 f = new PgpSymEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Get <code>public.pgp_sym_encrypt_bytea</code> as a field.
     */
    public static Field<byte[]> pgpSymEncryptBytea2(
          Field<byte[]> __1
        , Field<String> __2
        , Field<String> __3
    ) {
        PgpSymEncryptBytea2 f = new PgpSymEncryptBytea2();
        f.set__1(__1);
        f.set__2(__2);
        f.set__3(__3);

        return f.asField();
    }

    /**
     * Call <code>public.uuid_generate_v1</code>
     */
    public static UUID uuidGenerateV1(
          Configuration configuration
    ) {
        UuidGenerateV1 f = new UuidGenerateV1();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_generate_v1</code> as a field.
     */
    public static Field<UUID> uuidGenerateV1() {
        UuidGenerateV1 f = new UuidGenerateV1();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_generate_v1mc</code>
     */
    public static UUID uuidGenerateV1mc(
          Configuration configuration
    ) {
        UuidGenerateV1mc f = new UuidGenerateV1mc();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_generate_v1mc</code> as a field.
     */
    public static Field<UUID> uuidGenerateV1mc() {
        UuidGenerateV1mc f = new UuidGenerateV1mc();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_generate_v3</code>
     */
    public static UUID uuidGenerateV3(
          Configuration configuration
        , UUID namespace
        , String name
    ) {
        UuidGenerateV3 f = new UuidGenerateV3();
        f.setNamespace(namespace);
        f.setName_(name);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_generate_v3</code> as a field.
     */
    public static Field<UUID> uuidGenerateV3(
          UUID namespace
        , String name
    ) {
        UuidGenerateV3 f = new UuidGenerateV3();
        f.setNamespace(namespace);
        f.setName_(name);

        return f.asField();
    }

    /**
     * Get <code>public.uuid_generate_v3</code> as a field.
     */
    public static Field<UUID> uuidGenerateV3(
          Field<UUID> namespace
        , Field<String> name
    ) {
        UuidGenerateV3 f = new UuidGenerateV3();
        f.setNamespace(namespace);
        f.setName_(name);

        return f.asField();
    }

    /**
     * Call <code>public.uuid_generate_v4</code>
     */
    public static UUID uuidGenerateV4(
          Configuration configuration
    ) {
        UuidGenerateV4 f = new UuidGenerateV4();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_generate_v4</code> as a field.
     */
    public static Field<UUID> uuidGenerateV4() {
        UuidGenerateV4 f = new UuidGenerateV4();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_generate_v5</code>
     */
    public static UUID uuidGenerateV5(
          Configuration configuration
        , UUID namespace
        , String name
    ) {
        UuidGenerateV5 f = new UuidGenerateV5();
        f.setNamespace(namespace);
        f.setName_(name);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_generate_v5</code> as a field.
     */
    public static Field<UUID> uuidGenerateV5(
          UUID namespace
        , String name
    ) {
        UuidGenerateV5 f = new UuidGenerateV5();
        f.setNamespace(namespace);
        f.setName_(name);

        return f.asField();
    }

    /**
     * Get <code>public.uuid_generate_v5</code> as a field.
     */
    public static Field<UUID> uuidGenerateV5(
          Field<UUID> namespace
        , Field<String> name
    ) {
        UuidGenerateV5 f = new UuidGenerateV5();
        f.setNamespace(namespace);
        f.setName_(name);

        return f.asField();
    }

    /**
     * Call <code>public.uuid_nil</code>
     */
    public static UUID uuidNil(
          Configuration configuration
    ) {
        UuidNil f = new UuidNil();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_nil</code> as a field.
     */
    public static Field<UUID> uuidNil() {
        UuidNil f = new UuidNil();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_ns_dns</code>
     */
    public static UUID uuidNsDns(
          Configuration configuration
    ) {
        UuidNsDns f = new UuidNsDns();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_ns_dns</code> as a field.
     */
    public static Field<UUID> uuidNsDns() {
        UuidNsDns f = new UuidNsDns();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_ns_oid</code>
     */
    public static UUID uuidNsOid(
          Configuration configuration
    ) {
        UuidNsOid f = new UuidNsOid();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_ns_oid</code> as a field.
     */
    public static Field<UUID> uuidNsOid() {
        UuidNsOid f = new UuidNsOid();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_ns_url</code>
     */
    public static UUID uuidNsUrl(
          Configuration configuration
    ) {
        UuidNsUrl f = new UuidNsUrl();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_ns_url</code> as a field.
     */
    public static Field<UUID> uuidNsUrl() {
        UuidNsUrl f = new UuidNsUrl();

        return f.asField();
    }

    /**
     * Call <code>public.uuid_ns_x500</code>
     */
    public static UUID uuidNsX500(
          Configuration configuration
    ) {
        UuidNsX500 f = new UuidNsX500();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.uuid_ns_x500</code> as a field.
     */
    public static Field<UUID> uuidNsX500() {
        UuidNsX500 f = new UuidNsX500();

        return f.asField();
    }

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> pgpArmorHeaders(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(persistence.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders pgpArmorHeaders(
          String __1
    ) {
        return persistence.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders pgpArmorHeaders(
          Field<String> __1
    ) {
        return persistence.db.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        );
    }
}
